### ISSUE TITLE
User stories for ‘Storage for Travel Record’ 

### ISSUE THREAD

**Issue by lemonshushu** [swsnu/swpp2021-team1#10]
- 여행 추가하는건 유나가 이미 Create repository로 커버해서 여긴 포함 안시킴.

#### Actor 

User who wants to upload/share their photos to the repo

#### Precondition

- The user has to be signed in.
- The user has to be a member of the repository where they want to upload the photos to.

#### Scenario

1. The user enters the repository they want.
2. The user clicks the ‘Upload’ button placed in the upper-right side of the ‘Photos’ section.
3. File selector window pops up, and the user selects photos from their local storage. (The user can only select image files. *e.g.*, `.jpg`, `.png`, …
4. The uploaded images get added to the photos grid in the ‘Photos’ section.

#### Exceptions

- The image dimension is too big.
  - Automatically resize the image to maximum 960 pixels?
- The file size is too big.
  - Limit single uploadable file size to 50MB?

#### Actor

User who wants to view a photo existing in a repo

#### Precondition

- The visibility of the repo should be set to ‘public’. If not, the user has to be a member of the repo.

#### Scenario

- (전체적으로 구글포토랑 비슷하게 하면 될듯)

1. The user browses between existing photos by scrolling up and down in the ‘Photos’ section.
2. The user finds an interesting photo, and clicks on that photo to zoom it up.
3. Then the user enters the focus view — The background goes darker, and the selected photo is zoomed in and placed in the center. The user can view details of the photo at below — comment(description on photo), the uploader of the photo, date taken, date uploaded, place taken

#### Actor

User who wants to take a private note on an existing photo

#### Precondition

- The user has to be a member of the repo which contains the photo they want to comment on.

#### Scenario

1. The user clicks on the photo from the grid on the ‘repository page > Photos’ section, and enters the focus mode.
2. The user clicks on the existing comment in the details field.
3. The comment text changes into an input field. Then the user can edit the content of the comment.
4. The user hits the `Enter` key. Then the input field turns again into a plain text, containing the new version of the comment.

#### Exceptions

- There is no existing comment in the photo.	
  - Instead of a comment, show a placeholder text(‘Add a comment…’) and make sure the user can add a comment in the same way via clicking on the placeholder.

#### Actor

User who wants to delete an existing photo in the repo

#### Precondition

- The user has to be a member of the repo which contains the photo they want to delete.

#### Scenario

1. The user clicks on the photo, and enters the focus mode.
2. At the most bottom, there is a button reading ‘Delete.’ The user clicks on this button.
3. An alert — ‘Are you sure to delete this photo? Proceed / Cancel’ — pops up. The user clicks on ‘Proceed’.
4. The photo is deleted. Focus view is closed, and the photo disappears from the grid.

#### Actor
An user who wants to delete multiple photos

#### Precondition
- The user has to be a member of the repo.
#### Scenario
1. The user enters the repo they want.
2. The user right-clicks on one of the photos they want to delete.
3. A context menu appears, and the user selects 'Multiple Select' menu from it.
4. On selecting 'Multiple Select' menu, the user can select as many photos as they want. On clicking each photo, a blue interlace appears around the photo as a sign that it is selected.
5. When finished selecting, the user right-clicks again on one of the photos they've selected.
6. A context menu appears. The user selects 'Delete all' from the menu.
7. The selected photos are deleted, and they disappear from the photos section.

#### Actor 

An user who wants to privately categorize the travel photos for their purpose (The actor is trying to assign photos  to  label ‘A’)

#### Precondition

- The user has to be a member of the repo.
- There has to be an existing label ‘A.’

#### Scenario

1. The user enters the repository page.
2. From the ‘Labels’ section, the user navigates to the label they want to assign to the photos.
3. The user clicks on the `+` button inside the section of the label. Then, selection is activated for the photos in ‘Photos’ section.
4. The user clicks on the photos they want to assign the label. They can toggle selected/unselected state for each photo by clicking on the photo.
5. When finished selecting photos, the user again clicks on the `+` button.
6. The selected photos appear on the photo view section of the label.

#### Actor

- An user who wants to organize their photos into a post and share their thoughts

#### Precondition

- There should be existing photos in the repo

##### Scenario 1
1. The user clicks on the ‘POSTS’ tab.
2. The user clicks on the `+` button in the posts section. Then the user is redirected to post create page.
3. The user clicks on the `+` button in the ‘Journey’ field. then the user selects a journey(repository) they want to post about, from a dropdown menu. Then, photos in the repository show up in the ‘Photos’ field below.
4. The user inspects the photos and the labels(displayed in the right bottom side of each photo) of them, and decide which photos to include in the post. If the user wants to see the photo bigger: they right-click on the photo, a context menu appears, the user selects 'View image' from the context menu. Then the background goes dark and the image is shown in focus mode(as in viewing photos in the repo page). If the user clicks on the 'X' mark on the upper-right side of the photo, or clicks elsewhere than the photo area, focus mode is closed and the user is back to the post create page.
5. The user clicks on the checkbox placed on the upper right side on each photo. The user does this ‘selecting’ on all photos they want to include in the post.
6. The user types in some text they want to post, in the ‘Text’ input field.
7. The user clicks on the ‘Create’ button on the bottom. Then the user is redirected to the post page they just created.
##### Scenario 2
1. The user enters a repo.
2. The user right-clicks on a photo, and a context menu appears. The user selects 'Multiple Select' from the menu.
3. The user clicks on photos they want to select. Then each photo is interlaced with blue to denote that it is selected.
4. The user right-clicks on one of the photos they selected. A context menu appears. The user selects 'Create a post' from the menu.
5. The user is redirected to post create page. In the 'Photos' section, the photos that the user has selected is marked as selected --- The checkbox on these photos are already checked. If they want, they can add more photos via clicking on checkboxes on other photos.
6. Same as 6~7 from Scenario 1.

#### Actor 

An user who wants to view an existing post

#### Precondition

The user should have permission to access the post (the post is public / the post is written by self / the user is a member of the repo the post is contained in)

##### Scenario 1 : Access a self-written post from the ‘POSTS’ tab

1. The user clicks on the ‘POSTS’ tab.
2. The user clicks on the thumbnail photo of the post they want to view. Then the user is redirected to the post view page.

##### Scenario 2 : Access a post from a repo page

1. The user enters the repo page.
2. The user clicks on the thumbnail photo of the post, in the ‘Posts’ section. The user is redirected to the post view page.

#### Exceptions

- The user tries to access a post they have no access permission.
  - Show an alert: ‘You have no permission to view this post.’ and redirect to previous page

#### Precondition
The user has to be a member of that repo.
#### Scenario
1. The user enters the repo.
2. The user clicks on the '+ New Label' link on the 'Labels' section.
3. A prompt shows up: 'Enter a new label name:', and the user inputs a new label name, and hits `Enter`.
4. The new label name is added beside existing labels at the Labels section. Also, new row for the label appears at the bottom of existing rows for other labels.
5. The user clicks on the label icon, and a file selector window pops up.
6. The user selects an icon image from their local storage, and uploads it.
7. The icon image is set to the image the user has selected.
#### Exceptions
- The icon image dimension is not a square(정사각형).
	- Prompt the user to select only a square-shaped image.
- The icon image dimension is too big.
	- Limit the icon size to at most 256*256.

**Comment by ddony8128** [comment]
photo 페이지에서 한꺼번에 여러 사진을 삭제하고 싶을 때의 user story도 써주면 좋을 것 같아

서술된 label 관련 story의 전제조건이 이미 label이 존재하는 경우니까, 원하는 label을 추가하는 경우도 써주면 좋을 것 같고
label 별로 나누어진 사진을 보는 경우의 story도 적어주면 좋을 것 같아

upload a post에서 우리 회의 때 얘기했던 photo 마다의 comment에 대한 얘기도 넣어줘야 할 것 같아. 그리고 자기 페이지에서 게시글 올리는 버튼 눌러서 그 다음에 어느 repo에 올릴 건지 정하게 되어있는데, 각 repo의 게시글 페이지에서 게시글 올리는 버튼을 누름으로써 어느 repo에 올릴 건지 정해져 있는 상태에서 글 작성을 시작하는 시나리오도 따로 있으면 좋을 것 같아.

 각 사진/게시글 공개 범위를 private(자신만 볼 수 있음)/group(그룹에 속한 사람만 볼 수 있음)/public(모든 사람이 볼 수 있음) 세 가지로 나누는 건 어떻게 생각해? view a post에서 precondition으로 세 가지 조건이 지정되어 있는데, 마지막 조건이 그 글이 group으로 설정되어 있으면서 user가 그 그룹의 일원이라는 식으로 바꾸고.
