### ISSUE TITLE
'Settings' contents

### ISSUE THREAD

**Issue by lemonshushu** [swsnu/swpp2021-team1#11]
1. Global
   - Edit profile
     - Change username
     - Edit bio
   - Change account details
     - Change email
     - Change password
2. Repo-specific
   - Visibility
     - This repo is visible to (anyone / only members / members and members’ friends)
   - Fork permission
     - Allow (anyone/friends) to fork this repo
   - Manage members
     - Invite new member
     - Leave this repository
   - Delete repo
     - Delete this repository

일단 생각나는거만 ㅈ적어봤는데 생각나는대로 더 추가하겠음

**Comment by lemonshushu** [comment]
> bio가 뭐야?

자기소개..!

**Comment by ddony8128** [comment]
아하..!

repo specific setting에 권한 (repo 정보들, member 초대할 권리를 생성한 한 사람에게만 줄 건지 모든 멤버에게 동등하게 줄 건지), repo 정보 수정 (repo 제목 수정, 여행 기간 수정, 여행 장소 수정 ) 이 있어야 할 것 같아.
