### ISSUE TITLE
sprint 4 route API

### ISSUE THREAD

**Issue by youna1222** [swsnu/swpp2021-team1#114]
url | method | parameter | result | happening
-- | -- | -- | -- | --
/api/region-search/?query=[:query_string] | GET | - | list({place_id, formatted_address}) | -  
/api/repositories/[:repo_id]/route/ | GET | - | {repo_id, not_assigned: list({photo_id, repo_id, image, post_time, tag, uploader}), places: list({place_id, place_name, place_address, latitude, longitude, photos}), region: {region_address, place_id, latitude, longitude, north, south, west, east}} | -
| | POST | {place_id or repo_id} | - |query_string으로 요청할 경우 Google Map API에서 해당 place_id 정보 / route_id으로 요청할 경우 fork한 repo의 지도, markers와 함께 사진을 비운 places 칸들. Route가 생성됨은 물론, fork의 경우 PlaceInRoute 객체도 생성됨
/api/repositories/[:repo_id]/route/places-search/?query=[:query_string] | GET | - | list({place_id, formatted_address, name?}) | -
/api/repositories/[:repo_id]/route/places/[:place_id]/ | POST | - | list({place_id,  place_name, place_address, latitude, longitude, photos:list({photo_id, repo_id, image, post_time, tag, uploader})}) | PlaceInRoute가 생성되며 이때 order는 무조건 최댓값+1
/api/repositories/[:repo_id]/route/places/ | PUT | list({place_id,  place_name, place_address, latitude, longitude, text?, time?, thumbnail?, photos:list({photo_id, repo_id, image, post_time, tag, uploader})} | {not_assigned:list({photo_id, repo_id, image, post_time, tag, uploader}), places: list({place_id,  place_name, place_address, latitude, longitude, text?, time?, thumbnail?, photos:list({photo_id, repo_id, image, post_time, tag, uploader})} | -

* route를 가져오는 방식이 새 repo를 만들때 지역 이름으로 검색 또는 repo_name으로 검색하여 fork 두 가지이므로 ?로 주는 parameter에 따라 구분함
* search해서 google map에서던 repo fork로던 route가 확정되어서 POST 할때는 place_id를 보내줌. place_id는 Google Map API geocoding 중 place를 unique 하게 정의해주는 속성으로, search 시에 latitude, longitude 등과 함께 반환해줄거고, Route, Place 데베에도 추가되어야 할 속성.
* 어차피 지도는 한개이고 처음 설정할때던 수정할때던 search 해서 그 중에 선택해서 보내는거라 방법이 일치한다고 생각하여 POST, PUT은 구분하지 않았는데 필요할 경우 이야기해주면 구분하겠음
* route는 repo에 속하는거기도 하고 딱 하나여서 routes라고 안했는데, 통일성을 원할 경우 수정하겠음
* route 상의 marker(places와 해당 place의 text plan, order 등) 수정은 수정하기 버튼을 누르고 자유롭게 지울건 지우고, 수정할껀 수정한 다음에 한꺼번에 confirm 누르는 방식이 제일 나을 것 같아서 일단 그렇게 해봄.(따라서 PUT 시 list 전체를 보내줘야 하고, delete는 따로 없음)

**Comment by Queist** [comment]
sprint 4 아님..?

**Comment by Queist** [comment]
https://github.com/swsnu/swpp2021-team1/issues/86

유나야 이것도 만들어주면 좋을 것 같아
특정 레포의 사진을 장소에 따라 분류해서 IPlace 배열에 IPhoto들을 담아 반환하는 요청
내가 자세한건 states/action에 쓸게

**Comment by Queist** [comment]
유나야 생각해봤는데 세 번째 요청 POST보단 PUT이 맞지 않아..?

**Comment by Queist** [comment]
아래에서 두 번째 POST 리턴 값 수정 요청 : IPlace 대신 IPlace[] (해당 레포의 전체 배열)
