### ISSUE TITLE
RepoPost

### ISSUE THREAD

**Issue by youna1222** [swsnu/swpp2021-team1#138]
1. models
- Repository에 travel 필드가 추가됨. enum 중 RepoTravel.TRAVEL_OFF(0), RepoTravel.TRAVEL_ON(1)로 구분
- Post에 post_type 필드가 추가됨. enum 중 PostType.PERSONAL(0), PostType.REPO(1)로 구분.
2. api - POST
- 기존에 있던 postAPI에서 repositories/<int:repo_id>/posts/ 의 POST method 동일하게 사용하되, request body에 {"post_type": PostType.REPO} 포함해서 보내면 됨. 기존의 코드에는 이미 다 없으므로 백과 프런트의 편의를 위해 post_type이 따로 담겨있지 않을 경우 PostType.PERSONAL이 디폴트.
- 레포지토리 트레블로 생성되는 post_id, repository. post_type은 특이사항 없음. author는 백엔드 데베 상에서는 이미 one-to-one 필드이기 때문에 그냥 트레블하기를 누른 request.user를 저장할 것. 프론트는 신경쓸 필요없음.
- 프런트에 돌려주는 'author' 에는 collaborators list(username, bio, profile_picture)를 돌려줄 것. 이 때문에 주요 변경사항 - 기존의 IPost의 author가 리스트로 주고받게 됨. 기존의 personal post 역시 author 한명만을 포함하는 리스트로 통일하여 돌려줄것.
- title은 repository.repo_name이 제일 적합할 것 같아서 그렇게 돌려줄게
- text는 그냥 "" 돌려줄테니까 사용 안하면 될듯
2. api - PUT
- 기존에 있던 postAPI에서 repositories/<int:repo_id>/posts/ 에 오로지 레포지토리 트레블만을 위한 PUT method 추가할것. request body에 {"post_type": PostType.REPO, "travel": RepoTravel.ON/OFF} 없는데 이 method 콜하면 BadRequest 띄울것.
- 여기서는 오로지 travel 필드의 on/off 만 수정가능
3. api - GET (list, 특정 post_id 구분)
- post list GET 하는건 지금은 repository post 밖에 없는데 여기선 어차피 travel로 생성된 post를 추가하지는 않기로 했으므로 변경사항 없음. 백엔드에서 알아서 travel로 생성된 post는 repo에 속하지만 response에 포함 안되도록 관리할것
- post_id GET하는건 기존에 있던 postAPI에서 posts/<int:post_id>/의 GET method 동일하게 사용할것. reponse의 IPost에서 post_type 보고 traveling..? 해주세요
4. 프런트의 IPost 변경사항
- post_type 추가(없으면 디폴트로 personal post)
- author는 배열로 주고받음

**Comment by ddony8128** [comment]
👍 🥇
