### ISSUE TITLE
User stories for 'Function as SNS'

### ISSUE THREAD

**Issue by ddony8128** [swsnu/swpp2021-team1#14]
### Looking around feed while not logged-in

- Actor : Not logged-in user who wants to take a look at feed
- Precondition
  - The user is not signed in.
  - The user selected to pass the log-in page or enter into feed page directly.
- Scenario
1. The user scrolls up and down, see the posts one by one.
  2. The user can see posts that is public, was uploaded in recent 24 hours and have been gotten the most numerous likes.
  3. In each post in the feed, the user can scroll left and right to see all photos with descriptions attached to the post.
  4. The user can check how many likes the posts have been gotten below the photos.
  5. When click the like button, the user sees an alert which asks for log-in. If the user says yes, then the page redirects to log-in page. Else if the user says no or close the alert, the page just remains.
  6. When click the post (photos or descriptions), the user can read all contents and comments.
  7. When click the comment add space,  the user sees an alert which asks for log-in. If the user says yes, then the page redirects to log-in page. Else if the user says no or close the alert, the page just remains.
  8. When click the profile photo above the post, the user moves into the profile page of the post uploader.
  9. When click the repository name above the post, the user moves into the repository main page.
- Exceptions
  There's no new posts anymore : user can just see the logo image and a warning message on the feed.

### Looking around feed while logged-in

- Actor : User who wants to take a look at feed
- Precondition
  - The user has to be signed in.
- Scenario
1. The user scrolls up and down, see the posts one by one.
  2. The user can see posts of friend's repositories and the user's repository.
  3. If the user scrolls down enough to posts of friend's and the user's are over than The user can see posts that is public, was uploaded in recent 24 hours and have been gotten the most numerous likes.
  4. In each post in the feed, the user can scroll left and right to see all photos with descriptions attached to the post.
  5. The user can check how many likes the posts have been gotten below the photos.
  5. When click the like button, the user leaves a 'like reaction' to the post. 
  6. When click the post (photos or descriptions), the page redirects to post detail page and the user can read all contents and comments.
  7. When click the comment add space, the user can input comment texts.
  8. When click + button after inputting comment texts, the comment is uploaded and the page refreshes automatically.
  9. The user can also click the like button in the post detail page.
  10. When click the profile photo above the post, the user moves into the profile page of the post uploader.
  11. When click the repository name above the post, the user moves into the repository main page.
- Exceptions
  There's no new posts anymore : user can just see the logo image and a warning message on the feed.

### Searching while not logged-in

- Actor : Not logged-in user who wants to search especial travel place/person/repository
- Precondition
  - The user is not signed in.
  - The user selected to pass the log-in page or enter into feed page directly.
- Scenario
1. The user clicks the 'search' tab and moves into the search page.
  2. The user clicks the 'search bar' and a cursor appears in it.
  3. While the user types something in the search bar, a drop list appears and show the predicted result divided into three parts: place/person/repository
  4. If the user click one of the predicted result, than text in the search bar becomes completed.
  5. If the user click the search button then the result shows up. The result lists are divided into three parts place/person/repository. If too many results exist, there is 'show more button'
  6. The user can click the top of three parts so that fold the parts and unfold it.
  7. The user can move into appropriate profile page or repository main page after clicking person/repository results.
  8. If the user clicks place result, the text in the search bar changes into the place name and search tab just shows result of repositories about travels in that place. 
 * search results are all public contents.
- Exceptions
 There's no appropriate results: the search tab shows just empty each part: place (no results) / person (no results) / repository (no results)

### Searching while logged-in

- Actor : Not logged-in user who wants to search especial travel place/person/repository
- Precondition
  - The user has to be signed in.
- Scenario
1. The user clicks the 'search' tab and moves into the search page.
  2. The user clicks the 'search bar' and a cursor appears in it.
  3. While the user types something in the search bar, a drop list appears and show the predicted result diveded into three parts: place/person/repository
  4. The user can check one of checkboxs named 'search among friends', 'search among my repositories', 'search among all' next to the search bar. Each of checkboxs mean search range.
  4. If the user click one of the predicted result, than text in the search bar becomes completed.
  5. If the user click the search button then the result shows up. The result lists are divided into three parts place/person/repository. If too many results exist, there is 'show more button'
  6. The user can click the top of three parts so that fold the parts and unfold it.
  7. The user can move into appropriate profile page or repository main page after clicking person/repository results.
  8. If the user clicks place result, the text in the search bar changes into the place name and search tab just shows result of repositories about travels in that place. 
 * search results are all public contents.
- Exceptions
 There's no appropriate results: the search tab shows just empty each part: place (no results) / person (no results) / repository (no results)

### Being friend with another user

- Actor : User who wants to be friend with another user
- Precondition
  - The user has to be signed in.
  - Two users are not already friends.
- Scenario
1. The user enters another user's profile page with clicking profile image or searching user name.
  2. The user can see profiles on the left side of the page.
  3. When click the 'add friend' button below the profiles, a notification is sended to that user.
  4. If that user allows the message in the notification or friend page, two users become friends.
- Exceptions
 That user declines the message: a notification lets the user know the friend ask was declined.

### Checking my friends

- Actor : User who wants to check the friends
- Precondition
  - The user has to be signed in.
- Scenario
1. The user enters the own profile page.
  2. The user clicks the 'friends' tab.
  3. Then friends list show up.
  4. The user can also search a friend among friends in the friend tab.
- Exceptions
 No friend exists: list says 'no friend'

### Unfriending

- Actor : User who wants to unfriend
- Precondition
  - The user has to be signed in.
- Scenario
1. The user enters the own profile page.
  2. The user clicks the 'friends' tab.
  3. Then friends list show up.
  4. The user can press 'unfriend' button on the right side of each friend item.
  5. The user can also search a friend among friends in the friend tab.
  6. Then the user can press 'unfriend' button on the right side of friend item shown up after searching.
- Exceptions
 The friend is not a friend already: alert 'the friend is already unfriended' and then the page refreshes.

### Checking common repository with friend

- Actor : User who wants to check common repositories with a certain friend
- Precondition
  - The user has to be signed in.
  - The user has to have a friend.
- Scenario 1
1. The user enters the own profile page.
  2. The user moves into the 'friend' tab.
  3. The friend list shows number of common repositories between unfriend button and the friend name like '10 repositories'.
  4. If the user clicks the text, a drop list with repositories rolls down.
  5. If the user clicks one of the repositories, the user moves into the repository.
- Scenario 2
1. The user searches the friend's name in the search tab.
  2. The user clicks the friend and moves into the profile page.
  3. The user can see repository list below the profile page (originally being friend button or notification box exists)
  4. If the user clicks one of the repositories, the user moves into the repository.
- Exceptions
 No common repository exists : shows '0 repository' and empty list and warning message.

### Checking another user's friends

- Actor : User who wants to check another user's friend list
- Precondition
  - The user has to be signed in.
  - Another user has to allow to show the friend list.
- Scenario
1. The user enters another user's profile page.
  2. The user moves into 'friends' tab.
  3. Another user's friend list without unfriend button shows up.
  4. The user can see how many common repository the friend have.
  5. If the user clicks the number of common repository, a drop list with repositories rolls down. 
  6. If the user clicks one of the repositories and it is not private, the user moves into the repository.
- Exceptions
 Another user does not allow to show the friend list : shows empty list and warning message.
 The user clicks private repository : an alert shows up and says the repository is private.

### Checking how popular a repository is

- Actor : User who wants to check how popular a repository is
- Precondition
  - The user has to be signed in.
  - The repository allows to see the statistics
- Scenario
1. The user enters the repository he/she wants by searching or repository tab.
  2. The user can see statistics including total number of likes in the repository / total number of comments in the repository / number of forks of the repository on the bottom of the repository main page.
- Exceptions
 The repository does not allow to see the statistics : the statistics part in the page just not appears

### Making a post with the travel route

- Actor : User who wants to upload/share travel route in the own repository
- Precondition
  - The user has to be signed in.
- Scenario
1. The user enters a own repository main page.
  2. The user clicks the ‘upload as post’ button placed in the right side of the route.
  3. Then the page redirects to post create page with route component.
  4. The user can select to post planned route / real travel route / comparing two route in that page.
  5. The user can write a text below the route.
  6. If the user click create button, then a post containing the travel route is uploaded.
  7. If the user click back button, the page redirects to the repository main page.
- Exceptions
 The route changes while writing the post and then the create button is clicked : alert 'the route has been changed' appears and refresh with newly changed route and original text.

### Seeing a travel route post in the feed

- Actor : User who wants to see a travel route post in the feed
- Precondition
  - The user doesn't have to be signed in.
  - The travel route post is public or opened to friends.
- Scenario
1. The user enters the feed page and find a travel route post among posts.
  2. The user can check how many likes the posts have been gotten below the photos.
  3. When click the like button, the user sees an alert which asks for log-in if not logged-in. (If the user says yes, then the page redirects to log-in page. Else if the user says no or close the alert, the page just remains.) The user leaves like reaction to the post if logged-in.
  4. When click the post (route), the user can read all contents and comments.
  5. When click the comment add space, the user sees log-in an alert which asks for log-in if not logged-in. (If the user says yes, then the page redirects to log-in page. Else if the user says no or close the alert, the page just remains.) The user can input comment and add a comment with 'leave a comment' button if logged-in.
  6. When click the representative photos of each location in the route, the photo becomes larger, and then if the user clicks the other part, the photo changes back.
- Exceptions

### Checking my notifications

- Actor : User who wants to check his/her notifications.
- Precondition
  - The user has to be signed in.
- Scenario
1. The user enters the own profile page.
2. There is a notification list below the profile part.
  3. If the user click the top of notification list then it pops up bigger in the page and the if the user clicks outside of the notification list, the list changes back.
  4. The notification shows likes / comments / friend ask / fork / new posts in the own repository. They are shown as grouped with post / repository if possible.
  5. If the user click the notification, the user moves into corresponding appropriate page among post page, repository main page, friends tab.
- Exceptions
  A notification does not exist anymore when clicked : alert "the notification does not exist anymore" and the page refreshes.

**Comment by ddony8128** [comment]
> * 로그인하는 팝업창을 띄우려고 한다는데, 그러면 우리가 원래 짠 로그인창 말고 새로 또 팝업용 로그인 페이지를 만들어야 되나? 그냥 원래 로그인 페이지로 리다이렉트는 안될라나?
 경고창을 띄우고 알겠다고 하면 로그인 페이지로 리다이렉트 시키는 식으로 바꿀게

> * Checking another user's friends에서 그중 하나로 이동할 수 있으려면, 친구가 몇개의 repo를 가지고 있는지 개수 말고도, 누르면 드롭다운 메뉴를 표시해서 레포를 선택할 수 있어야 하지 않을까?
  그 중 하나로 이동할 수 있다는 말이 * Checking common repository with friend 에 있는 거랑 같은 방식으로 작동한다는 뜻이었는데, 똑같이 자세히 써놓을게...

> * Seeing a travel route post in the feed에서 레포 이름이나 유저 프로필 사진 클릭했을때 이동하는건 부수적인거고 여기서 핵심은 아니니까 빼도 되지않을까?
 꽤 중요한 기능 아냐? 그거 없으면 다른 레포나 유저를 찾기 위해선 검색 과정을 거쳐야 하는데 검색은 어려워서 후반 스프린트 때 구현하게 될 거 같고, 그러면 지금 시점에서 다른 레포나 유저 페이지를 들어갈 방법이 없어. 일단 넣어두는 걸로 할게.

**Comment by lemonshushu** [comment]
> > * Seeing a travel route post in the feed에서 레포 이름이나 유저 프로필 사진 클릭했을때 이동하는건 부수적인거고 여기서 핵심은 아니니까 빼도 되지않을까?
> 
> 꽤 중요한 기능 아냐? 그거 없으면 다른 레포나 유저를 찾기 위해선 검색 과정을 거쳐야 하는데 검색은 어려워서 후반 스프린트 때 구현하게 될 거 같고, 그러면 지금 시점에서 다른 레포나 유저 페이지를 들어갈 방법이 없어. 일단 넣어두는 걸로 할게.

물론 기능 자체는 중요하지만, 내 말은 'Seeing a travel route post in the feed'라는 user story에서 핵심은 아니라는 거였어. 이 시나리오에서는 피드에 있는 여행경로를 보는게 목적이니까. 차라리 checking specific repository / checking a user's profile 같은 스토리를 따로 만들어서 여기에 시나리오 중 하나로 넣는게 나을듯하다는게 나의 생각이야

**Comment by ddony8128** [comment]
> > > * Seeing a travel route post in the feed에서 레포 이름이나 유저 프로필 사진 클릭했을때 이동하는건 부수적인거고 여기서 핵심은 아니니까 빼도 되지않을까?
> > 
> > 
> > 꽤 중요한 기능 아냐? 그거 없으면 다른 레포나 유저를 찾기 위해선 검색 과정을 거쳐야 하는데 검색은 어려워서 후반 스프린트 때 구현하게 될 거 같고, 그러면 지금 시점에서 다른 레포나 유저 페이지를 들어갈 방법이 없어. 일단 넣어두는 걸로 할게.
> 
> 물론 기능 자체는 중요하지만, 내 말은 'Seeing a travel route post in the feed'라는 user story에서 핵심은 아니라는 거였어. 이 시나리오에서는 피드에 있는 여행경로를 보는게 목적이니까. 차라리 checking specific repository / checking a user's profile 같은 스토리를 따로 만들어서 여기에 시나리오 중 하나로 넣는게 나을듯하다는게 나의 생각이야

알았어. 그렇게 시나리오 두 개 추가할게.
