### ISSUE TITLE
React Component UML

### ISSUE THREAD

**Issue by Queist** [swsnu/swpp2021-team1#24]
https://app.moqups.com/lKxvXrZUaaJxWTiS75hmSxT134ner2GU/view/page/a1d1341ad

규칙 1) dashed-line은 pop-up창으로 띄워짐을 의미
규칙 2) dotted-line은 여러 개 중에 하나를 스위칭한다는 의미
규칙 3) solid-line은 그 페이지로 리다이렉트 된다는 의미
규칙 4) 클래스의 아래 칸은 리디렉션을 매개하는 버튼들을 배치했음

예외) Repository Detail의 Group, Mine, RepoSetting은 dotted-line으로 연결되어야 하는데 너무 복잡해서 놔둠

추가사항 1) Post에 delete post 버튼 추가 안해놓음
추가사항 2) 아예 비어있는 것들은 아직 작성 안한 컴포넌트들

**Comment by ddony8128** [comment]
참고용
