### ISSUE TITLE
Sprint 2 역할 배분

### ISSUE THREAD

**Issue by Queist** [swsnu/swpp2021-team1#25]
수빈 - Reducer & Action 구현과 함께 Wiki에 작성 / 컴포넌트 관계 UML 수정 / Axios Design 만들기
진영 - Reducer & Action 구현과 함께 Wiki에 작성 / 프론트엔드 컴포넌트 목록 및 기능 설명 작성 / 구현된 모습 페이지별로 캡쳐해서 올리기
유나 - api 표 만들어서 올리기 / 스프린트 계획 표 보고 축약해서 Implementation Plan 다이어그램 및 표로 만들기
도현 - Table Schema(완성됨) / E-R Diagram / System Architecture 그림 만들기

할 사람 할당해서 가져가주시고 몇 개는 내가 미리 할당해놨는데 문제 있으면 알아서 바꿔주세요.

+) 전체 다할 필요 없고 이번 스프린트 분량만 우선 확실하게 하면 됩니다. (Implementation Plan은 다 해야하지만) 시간 남으면 다음 스프린트 분량 대략적으로 하고.

이 밖에도 Test Plan도 작성해야하는데 금방 하니까 일단 놔둬도 될듯.

**Comment by lemonshushu** [comment]
내가 Axios 디자인 할게
근데 정확히 뭐하는거지..? 조교님이 올려놓은 글에서는 못찾겠는데

**Comment by Queist** [comment]
> 내가 Axios 디자인 할게 근데 정확히 뭐하는거지..? 조교님이 올려놓은 글에서는 못찾겠는데

톡방 게시글 참조해줘 게시글에 다 예시 첨부했어

**Comment by youna1222** [comment]
api 표 할게요
