### ISSUE TITLE
System Architecture

### ISSUE THREAD

**Issue by lemonshushu** [swsnu/swpp2021-team1#26]
- [wiki link](https://github.com/swsnu/swpp2021-team1/wiki/Design-and-Planning#system-architecture)

Here you should describe the high-level architecture of your system: the major pieces and how they fit together. Use graphical notations as much as possible in preference to English sentences. For example, you could describe the architecture using UML, if your system lends itself to these descriptions. Try to use standard architectural elements (e.g., pipe-and-filter, client-server, event-based, model-view-controller). Make sure to describe the major interfaces between components, which you will describe in more detail in the "Design details" section below.

**Comment by ddony8128** [comment]
![image](https://user-images.githubusercontent.com/62324495/139525567-9384c19a-7063-4440-974c-760f9f53be30.png)
