### ISSUE TITLE
User Stories for Visualization and Treating the Travel Route

### ISSUE THREAD

**Issue by Queist** [swsnu/swpp2021-team1#5]
#### Actor 
Those who want to add already visited places to their travel route.
#### Precondition
1. User has logged in.
2. User is on the repository page of the travel.
3. User is the group member of the repository.
#### Scenario
1. User clicks "History" button bottom right to the "Route" text.
2. Tab will changed to 'history tab'.
3. User clicks "Edit" button at the history tab.
4. The page with list of places pops up.
5. User types place's name what he/she wants to add in the search bar at the top.
6. Recommandation based on typed place name will be dropped down from search bar.
7. If user selects one of recommandation, the search bar is populated with the name of the place and drop down list will be rolled up.
8. User clicks "+" button next to search bar. If drop down list hadn't rolled up, drop down list will be rolled up.
9. New place that was in the search bar is added in the list with "time" input field.
10. User can write visited time on the input field if they want.
11. User shuts down the page and travel route will be modified.
#### Exception
User clicks "+" button with invalid place name.
- System alert 'Cannot find such place' and search bar cleared.
#### Actor 
Those who want to add places where they want to visit on their travel route.
#### Precondition
1. User has logged in.
2. User is on the repository page of the travel.
3. User is the group member of the repository.
#### Scenario
1. User clicks "Plan" button next to the "History" button.
2. Tab will changed to 'plan tab'.
3. User clicks "Edit" button at the history tab.
4. The page with list of places pops up.
5. User types place's name what he/she wants to add in the search bar at the top.
6. Recommandation based on typed place name will be dropped down from search bar.
7. If user selects one of recommandation, the search bar is populated with the name of the place and drop down list will be rolled up.
8. User clicks "+" button next to search bar. If drop down list hadn't rolled up, drop down list will be rolled up.
9. New place that was in the search bar is added in the list with "time" input field.
10. User can write visited time on the input field if they want.
11. User shuts down the page and travel route will be modified.
#### Exception
User clicks "+" button with invalid place name.
- System alert 'Cannot find such place' and search bar cleared.
#### Actor
Those who want to edit places in their travel route on history tab or plan tab.
#### Precondition
1. User has logged in.
2. User is on the repository page of the travel.
3. User is on the tab what he/she will wants to modify.
4. User is the group member of the repository.
#### Scenario
1. User clicks "Edit" button at the history tab.
2. The page with list of places pops up.
3. User can reorder places in the list with drag-drop.
4. User can delete places in the list by clicking "X" button next to the places.
5. User can modify visited time by writing another text in the time input field.
6. User shut down the page and travel route will be modified.
#### Exception
Other user already modified path before the user complete modifying path.
- System alert 'Travel route had been modified. Refresh the page please.' and route not be modified.
#### Actor
Those who want to go to travel by copying travel route from other's repository.
#### Precondition
1. User has logged in.
2. User is on the other's repository page that he/she want to copy.
#### Scenario
1. User clicks "History" or "Plan" tab depending on which path he/she want to copy.
2. User clicks "Fork" button below the "Route" text.
3. System redirects to repository create page.
4. The repository create page indicates at the top which repository's travel route user copied to.
#### Exception
Owner of the repository delete the repository before clicking fork.
- System alert 'Repository had been deleted." and redirect user to the user's profile page.
Owner of the repository modified the travel route before clicking fork.
- System alert 'Travel route had been modified. Please refresh the page." and doesn't redirect to other page.
#### Actor
Those who want to compare planned travel route and real travel route.
#### Precondition
1. User has logged in
2. User is at the repository of the travel he/she want.
#### Scenario
1. User clicks "Compare" tab next to the "Plan" button.
2. System indicates both routes from history tab and plan tab.
3. Plan tab's travel route will be indicates with black lines and history tab's travel route will be indicates with thick hazy lines.
#### Exception
None yet.
#### Actor
Those who want to looking back travel memories based on travel routes.
#### Precondition
1. User has logged in.
2. User is at the repository of the travel he/she want.
#### Scenario
1. User clicks history tab.
2. User can find travel route and representative photos of travel places float above the places.
#### Exception
None yet.
#### Actor
Those who want to recall memories of the journey what he/she went on.
Those who want to experience someone else's journey.
#### Precondition
1. User has logged in.
2. User is at the repository of the journey he/she want to experience.
#### Scenario
1. User clicks "Journey" button next to the "Route" text.
2. System picks a few random pictures from each place on the travel route and sorts them in chronological order.
3. The page darkens and the first picture appears.
4. User can click on a picture to go to the next picture or click the "x" button in the upper right corner to exit "Journey" immediately.
5. If user clicks on a last picture, "Journey" exit and can see that he/she stays on the page before pressing the "Journey".
#### Exception
The repository does not have travel route on "History".
-"Journey" button has been disabled.
The repository does not contain sufficient photos of each travel place.
-"Journey" button has been disabled.

**Comment by ddony8128** [comment]
전반적으로 잘 쓴 거 같은데 추가해주면 좋을 거 같은 부분이 몇 개 있어

1. 각 여행 장소의 'representative photo'를 설정해주는 user story ( + 설정하지 않았을 때는 랜덤으로 보인다는 내용을 story 6에 추가)
2. 각 여행 장소에 있었던 날짜 / 시간을 기록하는 user story
 내 생각엔 여행 장소 목록에 각 장소에다가 대표 사진이랑 시간 정보를 추가하는 버튼과 입력란을 넣는 거면 충분할 거 같은데
3. story 1~3, 5 각각에 대해 자신이 소유한 repo에 대해서만 이 일을 하는 건지, 아니면 남이 소유한 repo일 수도 있는 건지 확실히 명시해주면 좋을 거 같음. 확실히 하려면 story를 분리해서 남의 repo에 들어가는 경우를 따로 서술해주는 것도 좋겠지만 지금 당장 그렇게까지 할 필요는 없을 거 같고.
4. story 4 에서 fork를 해오는 게 그 사람의 실제 여행 경로 뿐인지, 아니면 plan도 가져올 수 있는지, 가능하다면 그 선택은 어떻게 할 건지 확실히 명시해주면 좋을 것 같음

**Comment by lemonshushu** [comment]
- 장소에서 time input field는 직접 텍스트로 입력하게 할거야? 그럼 invalid한 날짜값이 들어갔을때 exception 처리도 해줘야될거같은데..! 아님 텍스트 대신 날짜 선택기를 넣어서 선택하게 하든가
- 여행하기 기능이 원래 사진 하나씩 자기가 넘기면서 보는거였나..? 슬라이드쇼처럼 자동으로 넘어가는게 아니라? (기억안남)
