### ISSUE TITLE
Make States & Action Table / Implement & Test postsSlice, discussSlice - 김진영

### ISSUE THREAD

**Issue by Queist** [swsnu/swpp2021-team1#55]
.

**Comment by Queist** [comment]
임시 저장용

특정 repository에 속한 post들 가져오기
특정 user가 작성한 post들 가져오기
post 업로드하기
특정 post 가져오기
특정 post 수정하기
특정 post 삭제하기
특정 post에 comment 달기
(특정 post의) 특정 comment 수정하기
(특정 post의) 특정 comment 삭제하기

* user 정보를 안넣어도 되는 경우 (다른 유저가 아닌 자기 자신 관련 내용이라 request.user에서 받아올 수 있는 경우) - 최대한 user 관련 정보를 explicit하게 전달하지 않고 request를 보낼 수 있었으면 좋겠음.

**Comment by Queist** [comment]
### States
|Model|State|Description|
|------|-----|------------|
|Post|isLoading|Pending server's response.|
||hasError|Occurs error during communicate with server.|
||currentPost|Currently viewing post.|
||postList|Currently viewing user's / repository's post list|

### Actions
|Model|Action|Function|
|------|-----|------------|
|Post|fetchPostsByUser|fetch `username`'s posts list.|
||fetchPostsByRepo|fetch `repo_id`'s posts list.|
||createPost|create `repo_id`'s post. (`username` is automatically assigned at `request.user`.) - return created `post` object.|
||fetchPost|fetch `post_id`'s post.|
||editPost|change `post_id`'s post to `post` object. - return edited `post` object.|
||deletePost|delete `post_id`.|
||createComment|create `post_id`'s post. - return added comment.|
||editComment|edit `comment_id`'s comment. - return edited comment.|
||deleteComment|delete `comment_id`'s comment.|

**Comment by Queist** [comment]
### States
|Model|State|Description|
|------|-----|------------|
|Discussion|isLoading|Pending server's response.|
||hasError|Occurs error during communicate with server.|
||currentDiscussion|Currently viewing post.|
||discussionList|Currently viewing user's / repository's post list|

### Actions
|Model|Action|Function|
|------|-----|------------|
|Discussion|fetchDiscussions|fetch `repo_id`'s discussion list.|
||createDiscussion|create `repo_id`'s discussion. (`username` is automatically assigned at `request.user`.) - API must return created `discussion` object.|
||fetchDiscussion|fetch `discussion_id`'s discussion.|
||editDiscussion|change `discussion_id`'s discussion to `discussion` object. - API must return edited `discussion` object.|
||deleteDiscussion|delete `discussion_id`'s discussion.|
||createComment|create `discussion_id`'s comment. - API must return added comment. (or comment list is okay.)|
||editComment|edit `comment_id`'s comment. - API must return edited comment.(or comment list is okay.)|
||deleteComment|delete `comment_id`'s comment.|

**Comment by Queist** [comment]
Post에 대한 이야기 :
post의 사진은 repository의 사진이기 때문에, post create에서 repository list 및 해당 repository에 대한 photo list에 대한 요청을 할 것임.
photo들은 이미 업로드가 되어있는 사진들이기 때문에 파일 업로드 방식이 아닌 photo의 url만 파라미터로 전달할 예정.

**Comment by Queist** [comment]
![image](https://user-images.githubusercontent.com/80395847/139631678-4b6642e4-3024-4c6e-8ed5-8d8ff3437aa1.png)

**Comment by ddony8128** [comment]
Idiscussion, Icomment 등 전부 다 프론트에서 처음 생성 요청 보낼 때는 id 값을 가지고 있지 않으니까 아마 물음표를 붙여주는 게 맞지 않나 싶네

**Comment by Queist** [comment]
> Idiscussion, Icomment 등 전부 다 프론트에서 처음 생성 요청 보낼 때는 id 값을 가지고 있지 않으니까 아마 물음표를 붙여주는 게 맞지 않나 싶네
지금까지 id 그냥 -1로 보내주고 있는 중이었는데 지금까지 한거 고치기 귀찮아서.... 음...

> 그리고 노파심에 하는 얘기지만 comment에서 parent_id로 통일해서 쓸 때 discussion과 post에 서로 겹치는 id들이 많을 거야
참고할게

> 이 말이 명시적으로 일치시켜서 보내주겠다는 거야 아니면 author 이름 안 보내줘도 백에서 처리해달라는 거야?
후자

> post의 text는 없으면 아예 안 보내주는 것보다 user 정보 받았을 때의 bio 처럼 빈 스트링 주고 받는 게 좋지 않을까?
알겠으 (근데 원래 그러려고 그랬는데..?)

> uploadPhotos action 설명 부분 확인 및 수정 좀.
수정함
