### ISSUE TITLE
api for sprint3

### ISSUE THREAD

**Issue by youna1222** [swsnu/swpp2021-team1#78]
url | method | parameter | result
-- | -- | -- | --
/api/repositories/ [:repo_id]/photos/ | GET | - | { list( { photo_id : int, repo_id : int, image : string, post_time : string("YYYY-MM-DD hh:mm:ss"), tag : string, # label #, # place #, uploader : string } )
  | POST | FILES[image] : list(file) | list( { photo_id : int, repo_id : int, image : string, post_time : string("YYYY-MM-DD hh:mm:ss"), tag : string, uploader :string, # label #, # place # } )
  | PUT | list( { photo_id : int, tag : string, # label #, # place # } ) | list( { photo_id : int, repo_id : int, image : string, post_time : string("YYYY-MM-DD hh:mm:ss"), tag : string, uploader :string, # label #, # place # } )
  | DELETE | list( { photo_id : int } ) | list( { photo_id : int, repo_id : int, image : string, post_time : string("YYYY-MM-DD hh:mm:ss"), tag : string, uploader :string, # label #, # place # } )
/api/repositories/:repo_id/photos/?criteria={"post_time"/"label"/"place"} | GET | - | list( list ( { photo_id : int, repo_id : int, image : string, post_time : string("YYYY-MM-DD hh:mm:ss"), tag : string, uploader : string, # label #, # place # } ) )
/api/repositories/:repo_id/photos/?post_time={post_time}&label={label}&place={place} | GET | - | list ( photo_id : int, repo_id : int, image : string, post_time : string("YYYY-MM-DD hh:mm:ss"), tag : string, uploader : string, # label #, # place # } )
/api/repositories/ [:repo_id]/discussions/ | GET | - | list( { discussion_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
  | POST | { title : string(max_length=120), text : string(max_length=1000) } | { discussion_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, text : string, post_time : string("YYYY-MM-DD hh:mm:ss"), comments: empty list }
/api/discussions/ [:discussion_id]/ | GET | - | { discussion_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, text : string, post_time : string, comments : list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } ) }
  | PUT | { title : string, text : string } | { discussion_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, text : string, post_time : string, comments : list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } ) }
  | DELETE | - | -
/api/discussions/ [:discussion_id]/comments/ | GET | - | list( { comment_id : int, parent : id, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
  | POST | { text : string } | list ( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
/api/discussions/ [:discussion_id]/comments/ [:discussion_comment_id]/ | GET | - | { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") }
  | PUT | { text : string } | list ( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
  | DELETE | - | list ( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
/api/users/ [:username]/posts/ | GET | - | list( { post_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, post_time : string("YYYY-MM-DD hh:mm:ss") }, photos : list( { photo_id :int, local_tag : string, image : string } ) )
/api/repositories/ [:repo_id]/posts/ | GET | - | list( { post_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, post_time : string("YYYY-MM-DD hh:mm:ss"), photos : list ( { photo_id : int, local_tag : string, image : string } ) )
  | POST | { title : string(max_length=120), text : string(max_length=1000), photos : list( { photo_id : int, local_tag : string } ) } | { post_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, text : string, post_time : string("YYYY-MM-DD hh:mm:ss"), photos : list( { photo_id : int, local_tag : string, image : string } ), comments : empty list }
/api/posts/ [:post_id]/ | GET | - | { post_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, text : string, post_time : string("YYYY-MM-DD hh:mm:ss"), photos : list( { photo_id : int, local_tag : string, image : string } ) , comments : list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } ) }
  | PUT | { title : string, text : string, photos : list ( { photo_id : int, local_tag : string } ) } | { post_id : int, repo_id : int, author : { username : string, bio : string, profile_picture? : string }, title : string, text : string, post_time : string("YYYY-MM-DD hh:mm:ss"), photos : list ( { photo_id : int, local_tag : string, image : string } ), comments : list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } ) }
  | DELETE | - | -
/api/posts/ [:post_id]/comments/ | GET | - | list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
  | POST | { text : string } | list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
/api/posts/ [:post_id]/comments/ [:post_comment_id]/ | GET | - | { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") }
  | PUT | { text : string } | list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
  | DELETE | - | list( { comment_id : int, parent_id : int, author : { username : string, bio : string, profile_picture? : string }, text : string, post_time : string("YYYY-MM-DD hh:mm:ss") } )
 /api/users/:username/profile-picture/ | POST | FILES[image] : file | - |
| | DELETE | - | - |

comment list는 시간 순으로 정렬, discussion과 post는 시간 역순으로 정렬

**Comment by youna1222** [comment]
1. Discussion_comment_id가 database diagram에 대문자로 시작돼서 일단 그렇게 했는데 의도한거야?
2. with full attributes라고 쓴건 진영이가 이슈에 올려둔거에서 각 객체마다 attribute 지정해둔거 전부 다 담고 있다는 뜻이야. discussion이랑 comment는 다 repo에 속해 있고 그들한테만 전체 보이는거니까 통일된다고 생각했는데 지적할 부분 있음 해줭

**Comment by ddony8128** [comment]
> 1. Discussion_comment_id가 database diagram에 대문자로 시작돼서 일단 그렇게 했는데 의도한거야?
> 2. with full attributes라고 쓴건 진영이가 이슈에 올려둔거에서 각 객체마다 attribute 지정해둔거 전부 다 담고 있다는 뜻이야. discussion이랑 comment는 다 repo에 속해 있고 그들한테만 전체 보이는거니까 통일된다고 생각했는데 지적할 부분 있음 해줭

1. 악 아니야 실수야!
2. 오켕

**Comment by ddony8128** [comment]
상태 코드 sprint 2 때와 마찬가지로 적용
ex) GET discussions 또는 GET discussions/discussion_id 를 했는데 그 repo의 collaborator가 아니라면 403을 보냄. 

 < status code >
 * 200 : GET 요청에 대한 정상적인 응답.
 * 201 : PUT, POST 요청에 대한 정상적인 데이터 수정/추가.
 * 202 : DELETE 요청에 대한 정상적인 데이터 삭제.
 * 204 : GET /api/token/ 에 대한 정상적인 응답.
 * 400 ( HttpResponseBadRequest() ) : 요청에 포함된 데이터에 꼭 필요한 속성이 존재하지 않는 경우에 대한 응답.
 * 401 ( HttpResponseNotLoggedIn() ) : 로그인이 필요한 요청을 로그인하지 않은 상태에서 보냈을 때의 응답. 대부분의 비로그인 상태의 GET 요청은 이에 해당하지 않고, 비로그인 상태의 PUT, DELETE, POST 등이 이에 해당함.
 * 403 ( HttpResponseNoPermission() ) : 권한이 없는 요청에 대한 응답. 로그인은 되어 있지만, 해당 계정이 데이터 열람 / 데이터 삭제 / 데이터 수정 / 데이터 추가를 할 권한이 없을 때에 해당함.
 * 404 ( HttpResponseNotExist() ) : GET 요청에 알맞은 데이터가 존재하지 않을 경우에 대한 응답. 주로 URL에 <int: id>가 포함되어 있는데 그에 해당하는 id가 존재하지 않을 경우에 해당함. 쿼리 스트링 (?owner={username} 같은 것) 으로 특정 쿼리에 대한 검색을 요청할 때 결과가 존재하지 않는 경우는 빈 결과로 응답할 뿐, 404 응답 코드를 보내지 않음.
 * 405 ( HttpResponseNotAllowed( 허용하는 METHOD 리스트 ) ) : 허용되지 않는 method 요청에 대한 응답.
 * 410 ( HttpResponseInvalidInput( ) ) : POST 또는 PUT 요청과 함께 전달된 json에 사용 불가능한 값이 포함되어 있을 때의 응답. 속성의 자료형 / 형식이 맞지 않거나 존재하지 않는 객체를 가리키는 정보 (username, repo_id 등등)가 속성으로 포함되어 있을 때에 해당함.
 * 411 ( HttpResponseAlreadyProcessed() ): 동시성 문제로 인해 해당 요청이 이미 수행되었을 때의 응답.

status_code 우선순위: 405 > 401 > 403 > 404 > 400 > 410 > 411

**Comment by youna1222** [comment]
우선순위 404>403이어야 하지 않을까?
예를 들어 comment인 경우 comment에서 discussion 찾아서 repoository 찾아서 collaborators에 안속해 있으면 403 띄우는 상황에서 없는거 가지려고 하면 404로 먼저 걸러지는 상황

**Comment by Queist** [comment]
photos post : i) uploader 따로 안보내줌, ii) formData라고 특별한 형식으로 사진 보내줄 예정, tag는 못 보내줄 수도 있음.

그 아래에도 전부 author은 안보내줌.

post에서 image url list로 보내준다고 그랬는데, 생각해보니까 post 만들 때 image의 tag도 수정할 수 있지 않아? 그게 그 post에서만 local하게 수정하는걸로 취급할꺼야 아니면 그냥 repo든 뭐든 그 image의 tag를 어디서 수정하든 항상 동기화되어있는거야? 전자라면 뭔가 백쪽에서 새롭게 만들어줘야하고 그렇지 않으면 그냥 우리가 photo에다가 put 보내서 알아서 처리할게.

나머지는 일단 ok.

**Comment by Queist** [comment]
+) 삭제 후 photo list 받는게 나을 것 같음.

**Comment by Queist** [comment]
post photo discussion comment(얘는 역순) 전부 시간순으로 주는게 편합니다.

**Comment by ddony8128** [comment]
모두 반영, design and planning wiki에 옮겨 적었음.
끗!
